# Generated by Django 3.1a1 on 2020-06-18 17:04

import django.core.validators
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(help_text='A valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='start_date',
            field=models.DateField(help_text='The earliest date you can start working.', validators=[jobs.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='website',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
