# Generated by Django 3.1a1 on 2020-06-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_auto_20200615_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
